#### Cleaned up script with exploratory analysis removed.

In [1]:
import pandas as pd

In [2]:
#import dirty data
df = pd.read_csv('welcome.csv', encoding='latin1')
df.columns = ['PMID', 'Publisher', 'Journal title', 'Article title', 'Cost']

## Identify 5 most common journals.

In [3]:
#change to lowercase
df['Journal title'] = df['Journal title'].apply(lambda x: str(x).lower())

#Remove unwanted characters from journal titles.
df['Journal title'] = df['Journal title'].apply(lambda x: str(x).replace(',', ''))
df['Journal title'] = df['Journal title'].apply(lambda x: str(x).replace(':', ''))
df['Journal title'] = df['Journal title'].apply(lambda x: str(x).replace('.', ''))

#Remove all whitespace.
df['Journal title'] = df['Journal title'].apply(lambda x: str(x).replace(' ', ''))

#Remove s from last word.
df['Journal title'] = df['Journal title'].apply(lambda x: str(x).rstrip('s'))

#Count and determine top 5 Journals.  
df['Journal title'].value_counts().head(5)

plosone                         200
journalofbiologicalchemistry     53
neuroimage                       29
nucleicacidsresearch             25
plospathogen                     24
Name: Journal title, dtype: int64

## Generate summary statistics of price per journal.

In [7]:
#Remove leading pound sign
df['Cost_mod'] = df['Cost'].apply(lambda x: x[1:])

#Remove dollar sign
df = df[df['Cost_mod'].apply(lambda x: str(x).find('$')) < 0]

#Convert object to float
df['Cost_mod'] = df['Cost_mod'].astype(float)

#Remove outlier prices -> assume data entry error
df = df[df['Cost_mod'] < 25000]

#Summary statistics for each journal
df.groupby(['Journal title']).describe().head(10)

                                                   Cost_mod            \
                                                      count      mean
Journal title
academyofnutritionanddietetic                           1.0  2379.540
acschemicalbiology                                      5.0  1418.186
acschemicalneuroscience                                 1.0  1186.800
acsnano                                                 2.0   668.140
actacrystallographicasectiond                           1.0   757.180
actacrystallographicasectiondbiologicalcrystall...      2.0   772.580
actacrystallographicasectionfstructuralbiologya...      2.0   796.635
actacrystallographyd                                    1.0   774.190
actad                                                   1.0   750.160
actadermatovenereologica                                1.0   653.960

                                                                         \
                                                           std      min
Journal title
academyofnutritionanddietetic                              NaN  2379.54
acschemicalbiology                                  507.309560   947.07
acschemicalneuroscience                                    NaN  1186.80
acsnano                                              35.708892   642.89
actacrystallographicasectiond                              NaN   757.18
actacrystallographicasectiondbiologicalcrystall...    1.640488   771.42
actacrystallographicasectionfstructuralbiologya...   15.605847   785.60
actacrystallographyd                                       NaN   774.19
actad                                                      NaN   750.16
actadermatovenereologica                                   NaN   653.96

                                                                         \
                                                          25%       50%
Journal title
academyofnutritionanddietetic                       2379.5400  2379.540
acschemicalbiology                                  1267.7600  1294.590
acschemicalneuroscience                             1186.8000  1186.800
acsnano                                              655.5150   668.140
actacrystallographicasectiond                        757.1800   757.180
actacrystallographicasectiondbiologicalcrystall...   772.0000   772.580
actacrystallographicasectionfstructuralbiologya...   791.1175   796.635
actacrystallographyd                                 774.1900   774.190
actad                                                750.1600   750.160
actadermatovenereologica                             653.9600   653.960


                                                          75%      max
Journal title
academyofnutritionanddietetic                       2379.5400  2379.54
acschemicalbiology                                  1294.7800  2286.73
acschemicalneuroscience                             1186.8000  1186.80
acsnano                                              680.7650   693.39
actacrystallographicasectiond                        757.1800   757.18
actacrystallographicasectiondbiologicalcrystall...   773.1600   773.74
actacrystallographicasectionfstructuralbiologya...   802.1525   807.67
actacrystallographyd                                 774.1900   774.19
actad                                                750.1600   750.16
actadermatovenereologica                             653.9600   653.96

## Challenge: find price by subject area

In [6]:
#change case in additional columns 
df['Publisher'] = df['Publisher'].apply(lambda x: str(x).lower())
df['Article title'] = df['Article title'].apply(lambda x: str(x).lower())

#Classify based on key words.  Classifies in order listed.

df.loc[df['Journal title'].str.contains('bio'), 'subject'] = 'biology'
df.loc[df['Journal title'].str.contains('cell'), 'subject'] = 'biology'
df.loc[df['Publisher'].str.contains('cell'), 'subject'] = 'biology'

df.loc[df['Journal title'].str.contains('chem'), 'subject'] = 'chemistry'
df.loc[df['Publisher'].str.contains('chem'), 'subject'] = 'chemistry'

df.loc[df['Journal title'].str.contains('biochem'), 'subject'] = 'biochemistry'

df.loc[df['Journal title'].str.contains('psyc'), 'subject'] = 'psychology'
df.loc[df['Journal title'].str.contains('mental'), 'subject'] = 'psychology'
df.loc[df['Journal title'].str.contains('emotion'), 'subject'] = 'psychology'
df.loc[df['Journal title'].str.contains('depression'), 'subject'] = 'psychology'
df.loc[df['Journal title'].str.contains('sleep'), 'subject'] = 'psychology'

df.loc[df['Journal title'].str.contains('obesity'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('health'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('hiv'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('aid'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('immun'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('virol'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('bacter'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('patho'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('nutri'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('epidem'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('malaria'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('disease'), 'subject'] = 'health/disease'
df.loc[df['Journal title'].str.contains('paras'), 'subject'] = 'health/disease'
df.loc[df['Article title'].str.contains('vaccine'), 'subject'] = 'health/disease'
df.loc[df['Article title'].str.contains('immun'), 'subject'] = 'health/disease'

df.loc[df['Journal title'].str.contains('physio'), 'subject'] = 'physiology'

df.loc[df['Journal title'].str.contains('animal'), 'subject'] = 'veterinary'
df.loc[df['Journal title'].str.contains('veterinary'), 'subject'] = 'veterinary'

df.loc[df['Journal title'].str.contains('neuro'), 'subject'] = 'neuroscience'
df.loc[df['Journal title'].str.contains('brain'), 'subject'] = 'neuroscience'
df.loc[df['Journal title'].str.contains('epilep'), 'subject'] = 'neuroscience'

df.loc[df['Journal title'].str.contains('pharma'), 'subject'] = 'pharmacology'

df.loc[df['Journal title'].str.contains('hepato'), 'subject'] = 'medical'
df.loc[df['Journal title'].str.contains('transpl'), 'subject'] = 'medical'
df.loc[df['Journal title'].str.contains('respiratory'), 'subject'] = 'medical'
df.loc[df['Journal title'].str.contains('blood'), 'subject'] = 'medical'
df.loc[df['Journal title'].str.contains('genetic'), 'subject'] = 'medical'
df.loc[df['Journal title'].str.contains('vision'), 'subject'] = 'medical'
df.loc[df['Journal title'].str.contains('derma'), 'subject'] = 'medical'
df.loc[df['Journal title'].str.contains('derma'), 'subject'] = 'medical'
df.loc[df['Journal title'].str.contains('endo'), 'subject'] = 'medical'
df.loc[df['Publisher'].str.contains('med'), 'subject'] = 'medical'
df.loc[df['Publisher'].str.contains('physician'), 'subject'] = 'medical'

df.loc[df['Journal title'].str.contains('child'), 'subject'] = 'pediatrics'
df.loc[df['Journal title'].str.contains('pedia'), 'subject'] = 'pediatrics'

#Medical last to catch all that are crossovers into medical (ie biomedical)
df.loc[df['Journal title'].str.contains('med'), 'subject'] = 'medical'

#Fill unclassified with other and reassign column.
df['subject'] = df['subject'].fillna('other')

#Describe.  Many journals remain classified in "other" catch all.  Continue refining classification.  Is there a simpler way?
df.groupby(['subject']).describe()

               Cost_mod                                               \
                  count         mean         std      min        25%
subject
biochemistry       36.0  1860.121111  457.241056   270.00  1800.0000
biology           219.0  2085.526530  920.902088   321.46  1548.5950
chemistry         109.0  1557.183853  586.875065   265.67  1188.3900
health/disease    290.0  1908.715759  611.451297    45.94  1526.1350
medical           352.0  1723.045227  607.905448     0.00  1294.0500
neuroscience      206.0  2066.692767  714.479286   480.93  1735.0325
other             722.0  1655.171357  931.136285   122.31   897.0400
pediatrics         20.0  2090.999500  303.648704  1280.00  1855.9425
pharmacology       28.0  2253.132143  530.088773  1063.31  1944.1800
physiology         16.0  1809.164375  505.490908   827.13  1340.5300
psychology         58.0  2586.619310  782.952555   364.17  2321.3800
veterinary          9.0  2297.587778  420.951861  1806.38  2040.0000


                     50%        75%       max
subject
biochemistry    1825.575  2100.0000   2488.17
biology         1956.000  2368.7750   4226.04
chemistry       1443.990  1743.8400   3906.43
health/disease  1898.495  2274.8875   4554.01
medical         1808.555  2100.0000   3938.82
neuroscience    2065.785  2400.0000   5760.00
other           1529.470  2251.1700  13200.00
pediatrics      2183.910  2290.1725   2645.85
pharmacology    2316.640  2438.3700   3000.00
physiology      1943.220  2155.6975   2400.00
psychology      2432.275  3000.0000   4099.71
veterinary      2400.000  2476.8500   3144.24